version: 1
accounts:
  - address: dev_main
    coins:
      - "180000000000000udev"
client:
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    bank:
      denom_metadata:
        - description: ""
          denom_units:
            - denom: "udev"
              exponent: "0"
              aliases: [ ]
            - denom: "dev"
              exponent: "6"
              aliases: [ ]
          base: "udev"
          display: "dev"
          name: "Developer Network"
          symbol: "DEV"
    staking:
      params:
        bond_denom: "udev"
    gov:
      deposit_params:
        min_deposit:
          - amount: "1000000000"
            denom: "udev"
      params:
        burn_proposal_deposit_prevote: false
        burn_vote_quorum: false
        burn_vote_veto: true
        expedited_min_deposit:
          - amount: "1500000000"
            denom: "udev"
        expedited_threshold: '0.667000000000000000'
        expedited_voting_period: 86400s
        max_deposit_period: 172800s
        min_deposit:
          - amount: "1000"
            denom: "udev"
        min_deposit_ratio: '0.010000000000000000'
        min_initial_deposit_ratio: '0.000000000000000000'
        proposal_cancel_dest: ''
        proposal_cancel_ratio: '0.500000000000000000'
        quorum: '0.334000000000000000'
        threshold: '0.500000000000000000'
        veto_threshold: '0.334000000000000000'
        voting_period: 172800s
    crisis:
      constant_fee:
        denom: "udev"
    mint:
      minter:
        inflation: "0.000000000000000"
      params:
        inflation_max: "0.020000000000000"
        inflation_min: "0.010000000000000"
        inflation_rate_change: "0.015000000000000"
        mint_denom: "udev"